//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hawk.Memcached {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hawk.Memcached.StringMessages", typeof(StringMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cache choose $$Bucket$$ for $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string cache_choose {
            get {
                return ResourceManager.GetString("cache choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache socket pick $$Key$$ $$HashCode$$ 的本地化字符串。
        /// </summary>
        internal static string cache_socket_pick {
            get {
                return ResourceManager.GetString("cache socket pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking socket $$ToString$$ as closed and available to return to avail pool 的本地化字符串。
        /// </summary>
        internal static string close_socket {
            get {
                return ResourceManager.GetString("close socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream appears to be dead, so closing it down 的本地化字符串。
        /// </summary>
        internal static string closing_dead_stream {
            get {
                return ResourceManager.GetString("closing dead stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket creation thread leaving for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string connect_thread_connect {
            get {
                return ResourceManager.GetString("connect thread connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not connect for $$timeout$$ milliseconds 的本地化字符串。
        /// </summary>
        internal static string connect_timeout {
            get {
                return ResourceManager.GetString("connect timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating initial connections $$InitConns$$ for host: $$Servers[i]$$ 的本地化字符串。
        /// </summary>
        internal static string create_initial_connections {
            get {
                return ResourceManager.GetString("create initial connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created and added socket: $$ToString$$ for host $$Servers[i]$$ 的本地化字符串。
        /// </summary>
        internal static string created_and_added_socket {
            get {
                return ResourceManager.GetString("created and added socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created socket $$ToString$$ for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string created_socket {
            get {
                return ResourceManager.GetString("created socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating $$Create$$ new SockIO objects 的本地化字符串。
        /// </summary>
        internal static string creating_sockets {
            get {
                return ResourceManager.GetString("creating sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 default 的本地化字符串。
        /// </summary>
        internal static string default_instance {
            get {
                return ResourceManager.GetString("default instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exception thrown while writing bytes to server on delete 的本地化字符串。
        /// </summary>
        internal static string delete_IOException {
            get {
                return ResourceManager.GetString("delete IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error deleting key: $$Key$$.  Server response: $$Line$$ 的本地化字符串。
        /// </summary>
        internal static string delete_key_error {
            get {
                return ResourceManager.GetString("delete key error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion of key: $$Key$$ from cache failed as the key was not found 的本地化字符串。
        /// </summary>
        internal static string delete_key_not_found {
            get {
                return ResourceManager.GetString("delete key not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletion of key: $$Key$$ from cache was a success 的本地化字符串。
        /// </summary>
        internal static string delete_success {
            get {
                return ResourceManager.GetString("delete success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ending self maintenance. 的本地化字符串。
        /// </summary>
        internal static string end_self_maintenance {
            get {
                return ResourceManager.GetString("end self maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SockIOPool finished shutting down. 的本地化字符串。
        /// </summary>
        internal static string end_socket_pool_shutdown {
            get {
                return ResourceManager.GetString("end socket pool shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error closing input stream for socket: $$ToString$$ for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string error_closing_input_stream {
            get {
                return ResourceManager.GetString("error closing input stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error closing output stream for socket: $$ToString$$ for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string error_closing_output_stream {
            get {
                return ResourceManager.GetString("error closing output stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error closing socket: $$ToString$$ for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string error_closing_socket {
            get {
                return ResourceManager.GetString("error closing socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred while trying to close socket. 的本地化字符串。
        /// </summary>
        internal static string failed_to_close_socket {
            get {
                return ResourceManager.GetString("failed to close socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to close SockIO obj for server: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string failed_to_close_socket_on_host {
            get {
                return ResourceManager.GetString("failed to close socket on host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to close socket : $$Socket$$ 的本地化字符串。
        /// </summary>
        internal static string failed_to_close_some_socket {
            get {
                return ResourceManager.GetString("failed to close some socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create connection to: $$Servers[i]$$ -- only $$j$$ created 的本地化字符串。
        /// </summary>
        internal static string failed_to_connect {
            get {
                return ResourceManager.GetString("failed to connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get SockIO obj for: $$Host$$ -- new socket is not connected 的本地化字符串。
        /// </summary>
        internal static string failed_to_get_socket {
            get {
                return ResourceManager.GetString("failed to get socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to TrueClose socket: $$ToString$$ for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string failed_to_true_close {
            get {
                return ResourceManager.GetString("failed to true close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown while flushing servers 的本地化字符串。
        /// </summary>
        internal static string flushall_IOException {
            get {
                return ResourceManager.GetString("flushall IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No servers to flush 的本地化字符串。
        /// </summary>
        internal static string flushall_no_servers {
            get {
                return ResourceManager.GetString("flushall no servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown while trying to get object from cache for key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string get_IOException {
            get {
                return ResourceManager.GetString("get IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memcached get command: $$Cmd$$ 的本地化字符串。
        /// </summary>
        internal static string get_memcached_command {
            get {
                return ResourceManager.GetString("get memcached command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memcached: got back $$Results$$ results 的本地化字符串。
        /// </summary>
        internal static string get_memcached_result {
            get {
                return ResourceManager.GetString("get memcached result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to get SockIO from uninitialized pool! 的本地化字符串。
        /// </summary>
        internal static string get_socket_from_uninitialized_pool {
            get {
                return ResourceManager.GetString("get socket from uninitialized pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Counter not found at key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string getcounter_counter_not_found {
            get {
                return ResourceManager.GetString("getcounter counter not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null key for getCounter() 的本地化字符串。
        /// </summary>
        internal static string getcounter_null_key {
            get {
                return ResourceManager.GetString("getcounter null key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown while getting from cache on GetMultiple 的本地化字符串。
        /// </summary>
        internal static string getmultiple_IOException {
            get {
                return ResourceManager.GetString("getmultiple IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memcached GetMultiple cmd:  $$Cmd$$ 的本地化字符串。
        /// </summary>
        internal static string getmultiple_memcached_command {
            get {
                return ResourceManager.GetString("getmultiple memcached command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memcached: got back $$Results$$ results 的本地化字符串。
        /// </summary>
        internal static string getmultiple_results {
            get {
                return ResourceManager.GetString("getmultiple results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetMultiple get socket count : $$Sockets$$ 的本地化字符串。
        /// </summary>
        internal static string getmultiple_socket_count {
            get {
                return ResourceManager.GetString("getmultiple socket count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 host 的本地化字符串。
        /// </summary>
        internal static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignoring dead host: $$Host$$ for $$Expire$$ms 的本地化字符串。
        /// </summary>
        internal static string ignoring_dead_host {
            get {
                return ResourceManager.GetString("ignoring dead host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memcached incr/decr command: $$Cmd$$ 的本地化字符串。
        /// </summary>
        internal static string incr_decr_command {
            get {
                return ResourceManager.GetString("incr-decr command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown while writing bytes to server on incr/decr 的本地化字符串。
        /// </summary>
        internal static string incr_decr_IOException {
            get {
                return ResourceManager.GetString("incr-decr IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error incr/decr key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string incr_decr_key_error {
            get {
                return ResourceManager.GetString("incr-decr key error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key not found to incr/decr for key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string incr_decr_key_not_found {
            get {
                return ResourceManager.GetString("incr-decr key not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to initialize with no servers 的本地化字符串。
        /// </summary>
        internal static string initialize_with_no_servers {
            get {
                return ResourceManager.GetString("initialize with no servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to initialize an already initialized pool 的本地化字符串。
        /// </summary>
        internal static string initializing_initialized_pool {
            get {
                return ResourceManager.GetString("initializing initialized pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing pool with following settings: \n\tinitial connections: $$InitConnections$$\n\tminimum connections: $$MinConnections$$\n\tmaximum connections: $$MaxConnections$$\n 的本地化字符串。
        /// </summary>
        internal static string initializing_pool {
            get {
                return ResourceManager.GetString("initializing pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown while trying to deserialize for key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string loaditems_deserialize_error {
            get {
                return ResourceManager.GetString("loaditems deserialize error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deserializing $$Class$$ 的本地化字符串。
        /// </summary>
        internal static string loaditems_deserializing {
            get {
                return ResourceManager.GetString("loaditems deserializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished reading from cache server 的本地化字符串。
        /// </summary>
        internal static string loaditems_finished {
            get {
                return ResourceManager.GetString("loaditems finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \tkey: $$Key$$; flags: $$Flags$$; length: $$Length$$ 的本地化字符串。
        /// </summary>
        internal static string loaditems_header {
            get {
                return ResourceManager.GetString("loaditems header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load items line: $$Line$$ 的本地化字符串。
        /// </summary>
        internal static string loaditems_line {
            get {
                return ResourceManager.GetString("loaditems line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieving object and stuffing into a string. 的本地化字符串。
        /// </summary>
        internal static string loaditems_retrieve_as_string {
            get {
                return ResourceManager.GetString("loaditems retrieve as string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SerializationException thrown while trying to deserialize for key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string loaditems_SerializationException {
            get {
                return ResourceManager.GetString("loaditems SerializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IOException thrown while trying to uncompress input stream for key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string loaditems_uncompression_IOException {
            get {
                return ResourceManager.GetString("loaditems uncompression IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main thread already running 的本地化字符串。
        /// </summary>
        internal static string main_thread_running {
            get {
                return ResourceManager.GetString("main thread running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance thread choked. 的本地化字符串。
        /// </summary>
        internal static string maintenance_thread_choked {
            get {
                return ResourceManager.GetString("maintenance thread choked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving socket for host $$Host$$ to busy pool ... socket: $$Socket$$ 的本地化字符串。
        /// </summary>
        internal static string move_socket {
            get {
                return ResourceManager.GetString("move socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need to create $$Need$$ new sockets for pool for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string need_to_create_new_sockets {
            get {
                return ResourceManager.GetString("need to create new sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need to remove $$NeedToClose$$ spare sockets for pool for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string need_to_remove_spare_sockets {
            get {
                return ResourceManager.GetString("need to remove spare sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 argument host cannot be null 的本地化字符串。
        /// </summary>
        internal static string null_host {
            get {
                return ResourceManager.GetString("null host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null or empty key given 的本地化字符串。
        /// </summary>
        internal static string null_key {
            get {
                return ResourceManager.GetString("null key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null value for key passed to delete() 的本地化字符串。
        /// </summary>
        internal static string null_key_delete {
            get {
                return ResourceManager.GetString("null key delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parameter cannot be null 的本地化字符串。
        /// </summary>
        internal static string parameter_cannot_be_null {
            get {
                return ResourceManager.GetString("parameter cannot be null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to read from closed socket 的本地化字符串。
        /// </summary>
        internal static string read_closed_socket {
            get {
                return ResourceManager.GetString("read closed socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing potentially hung connection from busy pool ... socket in pool for $$Time$$ms 的本地化字符串。
        /// </summary>
        internal static string removing_hung_connection {
            get {
                return ResourceManager.GetString("removing hung connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing stale entry from pool as it is past its idle timeout and pool is over max spare 的本地化字符串。
        /// </summary>
        internal static string removing_stale_entry {
            get {
                return ResourceManager.GetString("removing stale entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IOException while compressing stream.  Storing data uncompressed. 的本地化字符串。
        /// </summary>
        internal static string set_compression_failure {
            get {
                return ResourceManager.GetString("set compression failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression succeeded, size after: $$Size$$ 的本地化字符串。
        /// </summary>
        internal static string set_compression_success {
            get {
                return ResourceManager.GetString("set compression success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error storing data in cache for key: $$Key$$ -- length: $$Size$$. Server response: $$Line$$ 的本地化字符串。
        /// </summary>
        internal static string set_error {
            get {
                return ResourceManager.GetString("set error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to native handle obj 的本地化字符串。
        /// </summary>
        internal static string set_failed_to_native_handle_object {
            get {
                return ResourceManager.GetString("set failed to native handle object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to serialize obj: $$Object$$ 的本地化字符串。
        /// </summary>
        internal static string set_failed_to_serialize {
            get {
                return ResourceManager.GetString("set failed to serialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid encoding type used: $$Encoding$$ 的本地化字符串。
        /// </summary>
        internal static string set_invalid_encoding {
            get {
                return ResourceManager.GetString("set invalid encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exception thrown while writing bytes to server on set() 的本地化字符串。
        /// </summary>
        internal static string set_IOException {
            get {
                return ResourceManager.GetString("set IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key is null or cmd is null/empty for set() 的本地化字符串。
        /// </summary>
        internal static string set_key_null {
            get {
                return ResourceManager.GetString("set key null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 memcached cmd (result code): $$Cmd$$ ($$Line$$) 的本地化字符串。
        /// </summary>
        internal static string set_memcached_command_result {
            get {
                return ResourceManager.GetString("set memcached command result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data not stored in cache for key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string set_not_stored {
            get {
                return ResourceManager.GetString("set not stored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serializing for key: $$Key$$ for class: $$Class$$ 的本地化字符串。
        /// </summary>
        internal static string set_serializing {
            get {
                return ResourceManager.GetString("set serializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size prior to compression: $$Size$$ 的本地化字符串。
        /// </summary>
        internal static string set_size_prior {
            get {
                return ResourceManager.GetString("set size prior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storing data as a string for key: $$Key$$ for class: $$Class$$ 的本地化字符串。
        /// </summary>
        internal static string set_store_data_as_string {
            get {
                return ResourceManager.GetString("set store data as string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storing with native handler... 的本地化字符串。
        /// </summary>
        internal static string set_store_with_native_handler {
            get {
                return ResourceManager.GetString("set store with native handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data stored successfully with key: $$Key$$ 的本地化字符串。
        /// </summary>
        internal static string set_success {
            get {
                return ResourceManager.GetString("set success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to compress data 的本地化字符串。
        /// </summary>
        internal static string set_trying_to_compress_data {
            get {
                return ResourceManager.GetString("set trying to compress data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of avail pool for host $$Host$$ = $$Sockets$$ 的本地化字符串。
        /// </summary>
        internal static string size_of_available_pool {
            get {
                return ResourceManager.GetString("size of available pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of busy pool for host $$Host$$ = $$Sockets$$ 的本地化字符串。
        /// </summary>
        internal static string size_of_busy_pool {
            get {
                return ResourceManager.GetString("size of busy pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket or its streams already null in trueClose call 的本地化字符串。
        /// </summary>
        internal static string socket_already_closed {
            get {
                return ResourceManager.GetString("socket already closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket in avail pool is not connected: $$Socket$$ for host: $$Host$$ 的本地化字符串。
        /// </summary>
        internal static string socket_not_connected {
            get {
                return ResourceManager.GetString("socket not connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting self maintenance.... 的本地化字符串。
        /// </summary>
        internal static string start_self_maintenance {
            get {
                return ResourceManager.GetString("start self maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SockIOPool shutting down... 的本地化字符串。
        /// </summary>
        internal static string start_socket_pool_shutdown {
            get {
                return ResourceManager.GetString("start socket pool shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished reading from cache server 的本地化字符串。
        /// </summary>
        internal static string stats_finished {
            get {
                return ResourceManager.GetString("stats finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown while getting stats from server 的本地化字符串。
        /// </summary>
        internal static string stats_IOException {
            get {
                return ResourceManager.GetString("stats IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line: $$Line$$ 的本地化字符串。
        /// </summary>
        internal static string stats_line {
            get {
                return ResourceManager.GetString("stats line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No servers to check stats 的本地化字符串。
        /// </summary>
        internal static string stats_no_servers {
            get {
                return ResourceManager.GetString("stats no servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \tkey: $$Key$$; value: $$Value$$ 的本地化字符串。
        /// </summary>
        internal static string stats_success {
            get {
                return ResourceManager.GetString("stats success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closing socket for real: $$Socket$$, lifetime: $$Lifespan$$ 的本地化字符串。
        /// </summary>
        internal static string true_close_socket {
            get {
                return ResourceManager.GetString("true close socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get connection to: $$Server$$ 的本地化字符串。
        /// </summary>
        internal static string unable_to_connect {
            get {
                return ResourceManager.GetString("unable to connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get SockIOPool instance 的本地化字符串。
        /// </summary>
        internal static string unable_to_get_socket_pool {
            get {
                return ResourceManager.GetString("unable to get socket pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to write to closed socket 的本地化字符串。
        /// </summary>
        internal static string write_closed_socket {
            get {
                return ResourceManager.GetString("write closed socket", resourceCulture);
            }
        }
    }
}
